# Generated by Django 6.0.3 on 2026-03-24 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_message_status_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='chat_message_preview_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='chat_push_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=191)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20)),
                ('push_token', models.CharField(blank=True, max_length=255)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='api_mobiled_user_id_a96bba_idx'), models.Index(fields=['platform'], name='api_mobiled_platfor_249421_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='unique_mobile_device_per_user')],
            },
        ),
    ]
