# Generated by Django 6.0.3 on 2026-04-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_seed_car_catalog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='messagehiddenforuser',
            new_name='api_message_user_id_305194_idx',
            old_name='api_message_user_id_2b37cc_idx',
        ),
        migrations.RenameIndex(
            model_name='messagehiddenforuser',
            new_name='api_message_message_a10f55_idx',
            old_name='api_message_message_814346_idx',
        ),
        migrations.RenameIndex(
            model_name='usercarmodel',
            new_name='api_usercar_user_id_d62a3b_idx',
            old_name='api_usercar_user_id_b484eb_idx',
        ),
        migrations.RenameIndex(
            model_name='usercarmodel',
            new_name='api_usercar_car_mod_eacc43_idx',
            old_name='api_usercar_car_mod_5d4f50_idx',
        ),
    ]
