# Generated by Django 6.0.3 on 2026-04-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_api_message_user_id_2b37cc_idx_api_message_user_id_305194_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text_language',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='partrequest',
            name='description_language',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='partrequest',
            name='title_language',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.PositiveBigIntegerField()),
                ('field_name', models.CharField(max_length=50)),
                ('target_language', models.CharField(max_length=12)),
                ('source_language', models.CharField(blank=True, max_length=12)),
                ('source_hash', models.CharField(max_length=64)),
                ('translated_text', models.TextField()),
                ('provider', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='api_transla_entity__fb4136_idx'), models.Index(fields=['target_language'], name='api_transla_target__6ad63c_idx')],
                'constraints': [models.UniqueConstraint(fields=('entity_type', 'entity_id', 'field_name', 'target_language'), name='unique_translation_cache_entry')],
            },
        ),
    ]
