# Generated by Django 6.0.3 on 2026-04-19 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_message_text_language_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartRequestAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_request_accesses', to='api.conversation')),
                ('part_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='api.partrequest')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_part_request_accesses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_request_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='api_partreq_user_id_3fdc79_idx'), models.Index(fields=['part_request', 'status'], name='api_partreq_part_re_3582dc_idx'), models.Index(fields=['conversation', 'status'], name='api_partreq_convers_0d721e_idx')],
                'constraints': [models.UniqueConstraint(fields=('part_request', 'user'), name='unique_part_request_access_per_user')],
            },
        ),
    ]
