# Generated by Django 6.0.3 on 2026-06-08 22:44

import api.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_apiuser_blocked_at_apiuser_blocked_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='apiuser',
            managers=[
                ('objects', api.models.ApiUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='username',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='phone',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
