"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def _env_bool(value, default=False):
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "y", "on"}


def _env_int(value, default=None):
    if value is None or str(value).strip() == "":
        return default
    try:
        return int(str(value).strip())
    except ValueError:
        return default


def _env_list(name, default=""):
    value = os.getenv(name, default)
    if value is None:
        return []
    return [
        item.strip()
        for item in str(value).split(",")
        if item.strip()
    ]


def _append_unique(values, extras):
    seen = set(values)
    for item in extras:
        if item not in seen:
            values.append(item)
            seen.add(item)
    return values


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-change-me",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool(os.getenv("DEBUG"), default=True)

ENABLE_NGROK = _env_bool(os.getenv("ENABLE_NGROK"), default=False)
ALLOWED_HOSTS = _env_list(
    "ALLOWED_HOSTS",
    "127.0.0.1,localhost,testserver",
)
CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS")

if ENABLE_NGROK:
    ALLOWED_HOSTS = _append_unique(
        ALLOWED_HOSTS,
        [
            ".ngrok-free.app",
            ".ngrok-free.dev",
            ".ngrok.app",
            ".ngrok.dev",
            ".ngrok.io",
        ],
    )
    CSRF_TRUSTED_ORIGINS = _append_unique(
        CSRF_TRUSTED_ORIGINS,
        [
            "https://*.ngrok-free.app",
            "https://*.ngrok-free.dev",
            "https://*.ngrok.app",
            "https://*.ngrok.dev",
            "https://*.ngrok.io",
        ],
    )

TRUST_PROXY_HEADERS = _env_bool(
    os.getenv("TRUST_PROXY_HEADERS"),
    default=ENABLE_NGROK,
)
USE_X_FORWARDED_HOST = TRUST_PROXY_HEADERS
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if TRUST_PROXY_HEADERS
    else None
)


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'channels',
    'users',
    'market',
    'chat',
    'subscriptions',
    'api',
    'django_extensions',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DB_ENGINE = os.getenv("DB_ENGINE", "sqlite").lower()

if DB_ENGINE in {"postgres", "postgresql"}:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "auto_spare_db"),
            "USER": os.getenv("DB_USER", "postgres"),
            "PASSWORD": os.getenv("DB_PASSWORD", "postgres"),
            "HOST": os.getenv("DB_HOST", "127.0.0.1"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


AUTH_USER_MODEL = "api.ApiUser"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv("TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

CHANNEL_LAYER_BACKEND = os.getenv("CHANNEL_LAYER_BACKEND", "redis").strip().lower()
REDIS_HOST = os.getenv("REDIS_HOST", "127.0.0.1")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))

if CHANNEL_LAYER_BACKEND in {"memory", "inmemory"}:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [(REDIS_HOST, REDIS_PORT)],
            },
        }
    }

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "api.pagination.DefaultPagination",
    "EXCEPTION_HANDLER": "api.exceptions.custom_exception_handler",
    "PAGE_SIZE": 20,
}

SIMPLE_JWT = {
    "SIGNING_KEY": os.getenv("JWT_SIGNING_KEY", SECRET_KEY),
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=_env_int(os.getenv("JWT_ACCESS_LIFETIME_MINUTES"), default=30)
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=_env_int(os.getenv("JWT_REFRESH_LIFETIME_DAYS"), default=90)
    ),
    "ROTATE_REFRESH_TOKENS": _env_bool(
        os.getenv("JWT_ROTATE_REFRESH_TOKENS"),
        default=False,
    ),
    "BLACKLIST_AFTER_ROTATION": _env_bool(
        os.getenv("JWT_BLACKLIST_AFTER_ROTATION"),
        default=False,
    ),
}

CHAT_MAX_MEDIA_BYTES = int(os.getenv("CHAT_MAX_MEDIA_BYTES", str(5 * 1024 * 1024)))
CHAT_PRESENCE_TTL_SECONDS = int(os.getenv("CHAT_PRESENCE_TTL_SECONDS", "75"))
CHAT_TYPING_TTL_SECONDS = int(os.getenv("CHAT_TYPING_TTL_SECONDS", "8"))
CHAT_HEARTBEAT_INTERVAL_SECONDS = int(os.getenv("CHAT_HEARTBEAT_INTERVAL_SECONDS", "20"))
CHAT_TRACE_CONVERSATION_ID = _env_int(os.getenv("CHAT_TRACE_CONVERSATION_ID"))
CHAT_ALLOWED_MEDIA_TYPES = tuple(
    item.strip()
    for item in os.getenv(
        "CHAT_ALLOWED_MEDIA_TYPES",
        "text/plain,image/jpeg,image/png,image/webp,image/gif,application/pdf,video/mp4,"
        "audio/mpeg,audio/mp4,audio/aac,audio/x-m4a,audio/mp4a-latm,audio/ogg,"
        "audio/wav,audio/x-wav,audio/webm",
    ).split(",")
    if item.strip()
)

CHAT_LOG_LEVEL = os.getenv("CHAT_LOG_LEVEL", "INFO").upper()
FCM_SERVICE_ACCOUNT_FILE = os.getenv("FCM_SERVICE_ACCOUNT_FILE", "").strip()
FCM_ANDROID_MESSAGE_CHANNEL_ID = os.getenv(
    "FCM_ANDROID_MESSAGE_CHANNEL_ID",
    "chat_messages",
).strip() or "chat_messages"
FCM_ANDROID_ACTIVITY_CHANNEL_ID = os.getenv(
    "FCM_ANDROID_ACTIVITY_CHANNEL_ID",
    "chat_activity",
).strip() or "chat_activity"
TRANSLATION_ENABLED = _env_bool(os.getenv("TRANSLATION_ENABLED"), default=False)
TRANSLATION_PROVIDER = os.getenv("TRANSLATION_PROVIDER", "google").strip().lower()
TRANSLATION_SUPPORTED_LANGUAGES = tuple(
    item.strip().lower()
    for item in os.getenv("TRANSLATION_SUPPORTED_LANGUAGES", "en,ar,he").split(",")
    if item.strip()
)
TRANSLATION_GOOGLE_LOCATION = os.getenv(
    "TRANSLATION_GOOGLE_LOCATION",
    "global",
).strip() or "global"
GOOGLE_CLOUD_PROJECT = os.getenv("GOOGLE_CLOUD_PROJECT", "").strip()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "chat_verbose": {
            "format": "%(asctime)s %(levelname)s [%(name)s] %(message)s",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "chat_verbose",
        }
    },
    "loggers": {
        "chat": {
            "handlers": ["console"],
            "level": CHAT_LOG_LEVEL,
            "propagate": False,
        }
    },
}
