# Generated by Django 6.0.3 on 2026-03-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
