# Generated by Django 6.0.3 on 2026-03-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sparepart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='email',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('supplier', 'Supplier')], default='user', max_length=20),
        ),
    ]
